<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Huiyin(Cloris) He" />


<title>Star Digital Analysis</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-sm-12 col-md-4 col-lg-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-sm-12 col-md-8 col-lg-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Star Digital</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="index.html">Analysis</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Star Digital Analysis</h1>
<h4 class="author">Huiyin(Cloris) He</h4>
<h4 class="date">3/22/2021</h4>

</div>


<div id="part-1.-online-advertising-effectiveness" class="section level3">
<h3>Part 1. Online Advertising effectiveness</h3>
<pre class="r"><code>####read data####
star=read.csv(&#39;~/Documents/UCI/3. WINTER/BANA 277. CUST &amp; SOCIAL ANLYT/assignment 3. star digital/star_digital.csv&#39;)</code></pre>
<ul>
<li>Run a t-test to make sure that the difference in mean of the two groups are the same, indicating that the experimental setup is unbiased.
<ul>
<li>H0 : difference in mean = 0, the setup in the of control and test groups are the same</li>
<li>HA : difference in mean != 0, the setup in the of control and test groups are different</li>
</ul></li>
</ul>
<pre class="r"><code>####1. online advertising effectiveness####
  #sum up the impressions
star$Timp=rowSums(star[4:9])
  ##t-test####
control=star[star$test==0,]
test=star[star$test==1,]
  #check if they have the same variance
var(control$purchase)</code></pre>
<pre><code>## [1] 0.2498894</code></pre>
<pre class="r"><code>var(test$purchase) #same variance</code></pre>
<pre><code>## [1] 0.2499872</code></pre>
<pre class="r"><code>  #t-test
t.test(control$Timp,test$Timp,var.equal = TRUE)</code></pre>
<pre><code>## 
##  Two Sample t-test
## 
## data:  control$Timp and test$Timp
## t = 0.13602, df = 25301, p-value = 0.8918
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.8064813  0.9267599
## sample estimates:
## mean of x mean of y 
##  7.929217  7.869078</code></pre>
<p>With a p-value of 0.8918, we could not reject the null hypothesis, therefore concluding the two group setups are the same and we could proceed with further analysis.</p>
<p>We split the data into control and test group and then built a logistic regression model with independent variable: purchase, dependent variable: test</p>
<pre class="r"><code>  #model####
model=glm(purchase~ test,
          data=star, family=binomial())
summary(model) #seems to have a positive effect</code></pre>
<pre><code>## 
## Call:
## glm(formula = purchase ~ test, family = binomial(), data = star)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.186  -1.186   1.169   1.169   1.202  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -0.05724    0.03882  -1.474   0.1404  
## test         0.07676    0.04104   1.871   0.0614 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 35077  on 25302  degrees of freedom
## Residual deviance: 35073  on 25301  degrees of freedom
## AIC: 35077
## 
## Number of Fisher Scoring iterations: 3</code></pre>
<p>We assume the level of significance to be 0.1 because our case is in a business context. Since the p-value of the variable ‘test’ is 0.0614 which is less than 0.1, the variable “test” is statistically significant which indicates that exposing consumers to Star ads has a positive effect on purchasing the package.</p>
</div>
<div id="part-2.-frequency-effect-of-advertising-on-purchase" class="section level3">
<h3>Part 2. Frequency effect of advertising on purchase</h3>
<pre class="r"><code>####2. frequency effect####

  ####model including interaction terms####
model2=glm(purchase~Timp*test,data=star,family = binomial())
summary(model2) #positive effect</code></pre>
<pre><code>## 
## Call:
## glm(formula = purchase ~ Timp * test, family = binomial(), data = star)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -4.9145  -1.1266   0.1299   1.2156   1.2433  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.169577   0.042895  -3.953 7.71e-05 ***
## Timp         0.015889   0.002876   5.524 3.32e-08 ***
## test        -0.013903   0.045613  -0.305    0.761    
## Timp:test    0.015466   0.003207   4.823 1.42e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 35077  on 25302  degrees of freedom
## Residual deviance: 34190  on 25299  degrees of freedom
## AIC: 34198
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code>  #exponential of coefficients
exp(model2$coefficients) </code></pre>
<pre><code>## (Intercept)        Timp        test   Timp:test 
##   0.8440214   1.0160156   0.9861932   1.0155865</code></pre>
<pre class="r"><code>  #odds of test group
exp(model2$coefficients[2]+model2$coefficients[3]+model2$coefficients[4])#increases the odds by 1.76%</code></pre>
<pre><code>##     Timp 
## 1.017605</code></pre>
<pre class="r"><code>  #odds of control group
exp(model2$coefficients[2]) #increases the odds by 1.6%</code></pre>
<pre><code>##     Timp 
## 1.016016</code></pre>
<p>In the test group, with one unit increase in impression, there will be 1.76% increases in the chance of purchasing.</p>
<p>In the control group, with every additional unit increase in impression, there will be 1.60% increases in the chance of purchasing.</p>
<p>While the two numbers seem to be very close, the test group is still slightly higher than the control group on increasing the odds of purchasing. Thus, we can conclude that increasing the frequency of advertising will increase the probability of purchasing.</p>
</div>
<div id="part-3.-conversion-effectiveness-of-site-1-5-vs.-site-6" class="section level3">
<h3>Part 3. Conversion effectiveness of site 1-5 vs. site 6</h3>
<pre class="r"><code>####3. which site to advertise on ####

  ####model with interaction terms####
#sum of site 1-5
star$imp_15=rowSums(star[4:8])
model3=glm(purchase~imp_15+imp_6+imp_15*test+imp_6*test,data=star,family = binomial())
summary(model3)</code></pre>
<pre><code>## 
## Call:
## glm(formula = purchase ~ imp_15 + imp_6 + imp_15 * test + imp_6 * 
##     test, family = binomial(), data = star)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -5.1280  -1.1195   0.1185   1.2217   1.2472  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -0.166556   0.042533  -3.916 9.01e-05 ***
## imp_15       0.019452   0.003443   5.650 1.61e-08 ***
## imp_6        0.003978   0.004294   0.927 0.354179    
## test        -0.006087   0.045314  -0.134 0.893139    
## imp_15:test  0.014617   0.003794   3.852 0.000117 ***
## imp_6:test   0.013483   0.005405   2.494 0.012616 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 35077  on 25302  degrees of freedom
## Residual deviance: 34166  on 25297  degrees of freedom
## AIC: 34178
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code>  #site1-5:test
model3$coefficients</code></pre>
<pre><code>##  (Intercept)       imp_15        imp_6         test  imp_15:test   imp_6:test 
## -0.166555901  0.019451760  0.003978112 -0.006087146  0.014616686  0.013482809</code></pre>
<pre class="r"><code>exp(model3$coefficients[2]+model3$coefficients[4]+model3$coefficients[5]) #increases the odds by 2.84%</code></pre>
<pre><code>##   imp_15 
## 1.028376</code></pre>
<pre class="r"><code>  #site1-5:control
exp(model3$coefficients[2]) #increases the odds by 1.96%</code></pre>
<pre><code>##   imp_15 
## 1.019642</code></pre>
<pre class="r"><code>  #site6:test
exp(model3$coefficients[3]+model3$coefficients[4]+model3$coefficients[6]) #increases the odds by 1.14%</code></pre>
<pre><code>##    imp_6 
## 1.011439</code></pre>
<pre class="r"><code>  #site6:control
exp(model3$coefficients[3]) #increases the odds by 0.40%</code></pre>
<pre><code>##    imp_6 
## 1.003986</code></pre>
<p>For site 1-5: 1.028376 is the odds of purchasing in the test group for sites 1-5. So for the test group, increasing 1 unit of impression increases the odds of purchasing by 2.84% on site 1-5.</p>
<p>For site 6: 1.011439 is the odds of purchasing in the test group for site 6. So for the test group, increasing 1 unit of impression increases the odds of purchasing by 1.14% on site 6.</p>
<p>Thus, we can conclude that ads on site 1-5 are more effective in terms of conversion than site 1-5 since the increase of odds of purchasing for site 1-5 is more than site 6.</p>
</div>
<div id="part-4.-roi" class="section level3">
<h3>Part 4. ROI</h3>
<p>From Part 3, we found out that site 1-5 is more effective. For this part, we will take the cost of the ads on each website into account to determine which one has a better ROI.</p>
<p>Since there is an oversampling issue in our dataset, we have an issue with the biased estimate of the constant term. We included the following offset value in our model to recover the term.</p>
<p>Population conversion rate=0.00153; Sample conversion rate=0.50</p>
<pre class="r"><code># 4. ROI ####
  # model w/ offset ####
model4=glm(purchase~imp_15+imp_6+imp_15*test+imp_6*test,
           offset =rep(log(((1-0.00153)/0.00153)/((1-0.5)/0.5)),nrow(star)),
           data=star,family = binomial())
summary(model4)</code></pre>
<pre><code>## 
## Call:
## glm(formula = purchase ~ imp_15 + imp_6 + imp_15 * test + imp_6 * 
##     test, family = binomial(), data = star, offset = rep(log(((1 - 
##     0.00153)/0.00153)/((1 - 0.5)/0.5)), nrow(star)))
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -5.1280  -1.1195   0.1185   1.2217   1.2472  
## 
## Coefficients:
##              Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept) -6.647512   0.042533 -156.289  &lt; 2e-16 ***
## imp_15       0.019452   0.003443    5.650 1.61e-08 ***
## imp_6        0.003978   0.004294    0.927 0.354179    
## test        -0.006087   0.045314   -0.134 0.893139    
## imp_15:test  0.014617   0.003794    3.852 0.000117 ***
## imp_6:test   0.013483   0.005405    2.494 0.012616 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 35077  on 25302  degrees of freedom
## Residual deviance: 34166  on 25297  degrees of freedom
## AIC: 34178
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The cost of advertising at Site 1-5 is 25 dollars per thousand impressions and the cost of advertising at Site 6 is 20 dollars per thousand impressions. And a purchase results in a lifetime contribution of 1,200 dollars for Star Digital.</p>
<p>Next, we calculated ROI for both sites.</p>
<pre class="r"><code>  #calculate the ROI ####
  #site 1-5
new=data.frame(imp_15=1,imp_6=0,test=1)
predict15=predict.glm(model4,new,type=&#39;response&#39;)[1]
predict15 *1200 /25</code></pre>
<pre><code>## [1] 22.33976</code></pre>
<pre class="r"><code>  #site 6
new2=data.frame(imp_15=0,imp_6=1,test=1)
predict6=predict.glm(model4,new2,type = &#39;response&#39;)[1]
predict6*1200/20</code></pre>
<pre><code>## [1] 27.67693</code></pre>
<p>From the above comparison, we can see that site 6 has a higher ROI than site 1-5 and thus, Star Digital should put its advertising budget on site 6.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
